name: Compile M5Cardputer Sketch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          # 1. Добавляем URL в конфигурацию (с https://)
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls static-cdn.m5stack.com
          
          # 2. Обновляем индексы
          arduino-cli core update-index
          
          # 3. Устанавливаем ядро (M5Stack базируется на esp32)
          arduino-cli core install esp32:esp32

      - name: Install Libraries
        run: |
          # Установка необходимых библиотек
          arduino-cli lib install "M5Cardputer"
          arduino-cli lib install "M5Unified"
          arduino-cli lib install "M5GFX"

      - name: Compile Sketch
        run: |
          # Создаем папку для билда
          mkdir -p ./build
          
          # Компиляция. Убедитесь, что CardPC.ino лежит в папке CardPC/
          # FQBN для Cardputer в актуальном ядре: esp32:esp32:m5stack_cardputer
          arduino-cli compile --fqbn esp32:esp32:m5stack_cardputer --output-dir ./build CardPC/

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: m5cardputer-firmware
          path: ./build/*.bin
          
