name: Compile M5Cardputer Sketch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Platform
        run: |
          # Удаляем старый конфиг, если он был кривой
          rm -f /home/runner/.arduino15/arduino-cli.yaml
          
          # Переменная с правильным URL
          M5_URL="static-cdn.m5stack.com"
          
          # Обновляем индекс плат
          arduino-cli core update-index --additional-urls $M5_URL
          
          # Устанавливаем платформу esp32
          arduino-cli core install esp32:esp32 --additional-urls $M5_URL

      - name: Install Libraries
        run: |
          # Установка библиотек для Cardputer
          arduino-cli lib install "M5Cardputer"
          arduino-cli lib install "M5Unified"
          arduino-cli lib install "M5GFX"

      - name: Compile Sketch
        run: |
          mkdir -p ./build
          # Убедитесь, что ваш .ino файл лежит в папке CardPC (CardPC/CardPC.ino)
          # Используем FQBN для Cardputer
          arduino-cli compile --fqbn esp32:esp32:m5stack_cardputer --output-dir ./build ./CardPC

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: m5cardputer-firmware
          path: ./build/*.bin
          
