name: Compile M5Cardputer Sketch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          # Оставляем пустым, чтобы не лезла ошибка "unsupported protocol"
          additional-urls: "" 

      - name: Install ESP32 Platform
        run: |
          # 1. Полностью сносим папку настроек, где застрял битый URL
          rm -rf /home/runner/.arduino15
          
          # 2. Явно инициализируем конфиг с ПРАВИЛЬНЫМ URL
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls static-cdn.m5stack.com
          
          # 3. Обновляем индексы (теперь только из конфига)
          arduino-cli core update-index
          
          # 4. Устанавливаем ядро
          arduino-cli core install esp32:esp32

      - name: Install Libraries
        run: |
          arduino-cli lib install "M5Cardputer"
          arduino-cli lib install "M5Unified"
          arduino-cli lib install "M5GFX"

      - name: Compile Sketch
        run: |
          mkdir -p ./build
          # Компиляция папки CardPC
          arduino-cli compile --fqbn esp32:esp32:m5stack_cardputer --output-dir ./build ./CardPC

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: m5cardputer-firmware
          path: ./build/*.bin
          
